### ISSUE TITLE
前言部分的意见

### ISSUE THREAD

**Issue by yuconglin** [gaoxiang12/slam_in_autonomous_driving#10]
1. 参考书的reference [8] 不知道是不是名字要换一下，这两个链接里面的名字都是 State Estimation for Robotics, 没有后面的 a matrix lie group approach了。http://asrl.utias.utoronto.ca/~tdb, https://www.cambridge.org/core/books/state-estimation-for-robotics/AC0E0AC229C55203B3C8F106BCB61F48

2. Page 4里面提到的docker 好像还没有反映在github上。

**Comment by gaoxiang12** [comment]
1. 已修复。
2. docker目前还没ready，后面补上吧。
