### ISSUE TITLE
in Docker, Pangolin X11 : Failed to open X display

### ISSUE THREAD

**Issue by shuttworth** [gaoxiang12/slam_in_autonomous_driving#101]
<img width="501" alt="image" src="https://github.com/gaoxiang12/slam_in_autonomous_driving/assets/46838923/e2c4e2f6-9267-4a1d-b2ae-c1156ba308fc">

in Docker, how to solve?

**Comment by JohnsenJiang** [comment]
同问，![Snipaste_2023-08-08_10-35-52](https://github.com/gaoxiang12/slam_in_autonomous_driving/assets/15062041/0ff32caf-cc44-41c1-8221-0ef482127e90)

**Comment by zijiechenrobotics** [comment]
Hi @shuttworth , you can try this docker https://github.com/zijiechenrobotics/slam_in_autonomous_driving_docker, which specifically design for shenlan slam in autonomous driving course.
