### ISSUE TITLE
第四章代码运行报错

### ISSUE THREAD

**Issue by zyqdragon** [gaoxiang12/slam_in_autonomous_driving#113]
运行过程中输出信息如下:
I0904 19:52:20.316540 28670 static_imu_init.cc:71] mean acce: -0.612774 0.0203702 009.80743
--------cov_gyro_ 5.5781e-07
4.46347e-07
7.20772e-07
--------cov_acce_ 3.5829e-05
3.60427e-05
4.34496e-05
I0904 19:52:20.317546 28670 static_imu_init.cc:95] IMU 初始化成功，初始化时间= 9.99001, bg = -0.000306222 00.000156394 -8.89245e-06, ba = -0.00103346 3.43548e-05 000.0165404, gyro sq = 05.5781e-07 4.46347e-07 7.20772e-07, acce sq = 03.5829e-05 3.60427e-05 4.34496e-05, grav = 000.611741 -0.0203359 00-9.79089, norm: 9.81
I0904 19:52:20.317570 28670 static_imu_init.cc:99] mean gyro: -0.000306222 00.000156394 -8.89245e-06 acce: -0.00103346 3.43548e-05 000.0165404
Segmentation fault (core dumped)
哪位大佬能帮忙解答下么?

**Comment by gaoxiang12** [comment]
用git pull一下代码？我记得之前在关闭UI跑的话有个逻辑问题。
