### ISSUE TITLE
这段代码是C++17新特性么？请大神指路学习。

### ISSUE THREAD

**Issue by WangPei-hitman** [gaoxiang12/slam_in_autonomous_driving#114]
![2023-09-12_19-51](https://github.com/gaoxiang12/slam_in_autonomous_driving/assets/58885413/56f526e8-892b-45d9-bf26-06aa3ef225f2)
就是这里的template block，这里的template有什么用？请大神指路学习

**Comment by gaoxiang12** [comment]
不是，这个就是通常的写法。在模板函数里调用其他的模板函数，就得加上template关键字。在普通函数里可以省略，也可以写上。
