### ISSUE TITLE
第三章图像问题

### ISSUE THREAD

**Issue by yonuyeung** [gaoxiang12/slam_in_autonomous_driving#120]
请求解答，十分感谢！
在书的第60页，我运行出来的轨迹图是下面这样的，右上角四元数那里是qx，qy趋于零和课本不太一样，书上说的qy，qz趋于零

###### 我运行的

![3392976ddec1d5ca74f337ccf1dcaf1](https://s2.loli.net/2023/10/17/k8lFbEZMijWSqJv.png)

###### 书上的

![image-20231017193329995](https://s2.loli.net/2023/10/17/fgVKEdcj3FMvkHX.png)

**Comment by gaoxiang12** [comment]
sorry 这里有一个绘图脚本上的问题，四元数读取顺序和写入顺序不一致，我回头修复一下。

**Comment by yonuyeung** [comment]
好的，谢谢
