### ISSUE TITLE
书本课后题

### ISSUE THREAD

**Issue by w8128835** [gaoxiang12/slam_in_autonomous_driving#128]
高博，在本书第二章课后题第二题推导时和书中p36的2.100推导形式少了个log,个人初学者数学比较差，请问这个有标准答案可以对比学习吗？
其实不止这章，咱们这本书的课后题有什么方式获得参考答案吗，希望做出来至少知道自己推导等思路是否正确，害怕做错了而不自知 @gaoxiang12

**Comment by gaoxiang12** [comment]
知乎有老哥整理过一版，可以大概看看：https://www.zhihu.com/people/wang-kern/posts?page=1

**Comment by w8128835** [comment]
好的，谢谢高博~
