### ISSUE TITLE
Ch3,ESKF 中 IMU的坐标系问题

### ISSUE THREAD

**Issue by zvxvd** [gaoxiang12/slam_in_autonomous_driving#139]
请问在ESKF 融合时，IMU 应该采用哪种坐标系呢，我现在的IMU 为 前（X+），左（Y+），上（Z+），在使用我自己的数据进行融合时，发现估计的速度vel_x 和 vel_y 与实际速度差别很大，但是轨迹感觉是对的

下面是可视化的轨迹：绿色为RTK测量得到的原始位置，红色为IMU预测得到的位置
![image](https://github.com/gaoxiang12/slam_in_autonomous_driving/assets/155422487/29f773c2-3ee5-4daa-a3f8-08d5f4ed2fd7)

下面是pangolin 中 vel_x vel_y vel_z 和 baselink_vel_x ,baselink_vel_y ,baselink_vel_, 差别非常大

![image](https://github.com/gaoxiang12/slam_in_autonomous_driving/assets/155422487/26282953-6b9c-4b1e-bb84-2f5ae1bd1d24)

![image](https://github.com/gaoxiang12/slam_in_autonomous_driving/assets/155422487/1f954cd1-56ec-4bf9-aa66-de12deb10e7f)

![image](https://github.com/gaoxiang12/slam_in_autonomous_driving/assets/155422487/ca3d0169-078a-4e19-a622-a99c3ee4da38)

**Comment by gaoxiang12** [comment]
pangolin一个是本体下速度，一个是世界系下速度，中间实际相差一个旋转矩阵。当然这么说不严格，应该说是“世界速度矢量在本体系下的坐标表示”。

我看上去你的结果应该没问题的。

**Comment by zvxvd** [comment]
好的，谢谢高博
