### ISSUE TITLE
第二章建议: 第二部分

### ISSUE THREAD

**Issue by yuconglin** [gaoxiang12/slam_in_autonomous_driving#16]
我看的是230214 更新版本。

1. 式 (2.110) 的二次项可能缺了一个½的系数。
2. 式 (2.122) 感觉应该是 (J^{T} * Omega^{-1} * J) * Delta_{x} = - J^{T} * Omega^{-1} * e (如果不考虑累加的话)。我参考了barfoot书中文翻译版的第(4.125)式。

谢谢。

**Comment by gaoxiang12** [comment]
Hello,

1. 1/2系统可以直接归到H阵里，大部分材料是不带的。
2. 已经修复，见0215更新版本。

**Comment by qlibp** [comment]
ver. 230214
1. 式 (2.112)
   - 问题: 变量语义不够清晰, 等号左右都出现了 x_k, 因果性让人犯晕, 只有熟悉的人能知道表达什么意思. 
   - 建议: 参考barfoot书中(式4.24a)表述更佳![image](https://user-images.githubusercontent.com/43082379/220799343-a4e618d8-a9fb-432e-99a4-0c5e7eb3b98f.png)

**Comment by qlibp** [comment]
ver. 230214
1. 式(2.95) & 式(2.99) 
    - 疑问: 为什么式(2.95)是对扰动量的李代数求偏导, 式(2.99)是对SO(3)求偏导?

**Comment by gaoxiang12** [comment]
@qlibp 你另外开个issue吧，已经关闭的issue在我这边有时候没提示。
