### ISSUE TITLE
如何运行？How to run compiled code?

### ISSUE THREAD

**Issue by JaySlamer** [gaoxiang12/slam_in_autonomous_driving#24]
![Screenshot from 2023-02-22 13-36-56](https://user-images.githubusercontent.com/12229227/220532485-65c33d09-d88d-42f2-bd56-707bbf35cad0.png)
我直接运行bin文件夹下的可执行代码，出现如上错误，显然是ros的库没有被正确调用。这个工程似乎和一般的ros工程编译不太一样，把我整不会了：）。
烦请高博或其他路过的大佬指点下。

**Comment by gaoxiang12** [comment]
hello,
本书大部分程序需要在代码目录调用bin/xxx 来操作，和书里的指令是一样的。
class_loader大部分时候应该在安装ros时候，放到/opt/ros/noetic/lib/下面，通过source /opt/ros/noetic/setup.bash 引入。或者直接ldconfig 这个目录也可以。

**Comment by JaySlamer** [comment]
> source /opt/ros/noetic/setup.bash
谢高博解答。没书，小菜鸡一只，不敢提要当审稿人的请求😭。
