### ISSUE TITLE
阅读建议

### ISSUE THREAD

**Issue by gongjun136** [gaoxiang12/slam_in_autonomous_driving#30]
个人建议，不一定对：
[sad_book阅读建议2.pdf](https://github.com/gaoxiang12/slam_in_autonomous_driving/files/10833981/sad_book.2.pdf)

**Comment by gaoxiang12** [comment]
感谢，已经在3.6更新版本中修复。

**Comment by gongjun136** [comment]
> 感谢，已经在3.6更新版本中修复。

高博能发下最新的更新版本吗？3592754223@qq.com
