### ISSUE TITLE
第五章读后感

### ISSUE THREAD

**Issue by yuconglin** [gaoxiang12/slam_in_autonomous_driving#31]
根据2/21更新版本。个人观点，不一定对。

1. Page 121: 最后一句，”整体而言，自动驾驶使用的激光主要分为机械旋转式
雷达（spining Lidar）与固态雷达（solid state Lidar）两种形式”. 感觉这句话的意思让人理解起来没有问题，但还是有些不太严谨。感觉 “整体而言，自动驾驶使用的激光雷达主要分为机械旋转式（spining Lidar）与固态（solid state Lidar）两种形式” 这样也许会好些。

2. Page 122: 好像从这一页开始就直接用“雷达”代表激光雷达了，感觉是不是需要声明下，比如说本章用雷达代表激光雷达？不然可能会让人首先想到毫米波雷达。比如这句 “有些人认为 L4 自动驾驶离不开雷达，有些人则激烈地认为雷达是车辆的累赘”，如果不解释是激光雷达，会让人觉得有些疑惑。

3. https://github.com/gaoxiang12/slam_in_autonomous_driving/blob/master/src/ch5/kdtree.cc#L181 这里感觉用int idx 就够了。

4. https://github.com/gaoxiang12/slam_in_autonomous_driving/blob/master/src/ch5/kdtree.cc#L196 这里注释意思容易懂，但看代码的意思是上面的判定结果要么全部是负的，要么全部是正的?

5. https://github.com/gaoxiang12/slam_in_autonomous_driving/blob/master/src/ch5/octo_tree.cc#L110 这样的话感觉就没法考虑点云坐标是负值的情况了。(3, 4, 5 已经提交了一个pull request）

6. Page 162: “其中 Λ 为对角特征值矩阵，不妨令它的排列是从大到小的”. 这句话可能要改下，比如: “不妨令特征值的排列是....”.

7. Page 165: “其中 f 为点到直线的垂直距离” 这句话看起来有些多余？

谢谢高博

**Comment by gaoxiang12** [comment]
问题已确认，马上修复。
