### ISSUE TITLE
第7章小建议

### ISSUE THREAD

**Issue by gongjun136** [gaoxiang12/slam_in_autonomous_driving#34]
这部分的雷达里程计和lio系统最后只有地图没有精度分析，建议用ground truth坐下定量分析。
![image](https://user-images.githubusercontent.com/73570451/221892170-6528887e-01e5-445c-9dcd-6711afc1b166.png)

**Comment by gaoxiang12** [comment]
我会考虑，不过部分数据集不见得有GroundTruth，这篇主要介绍激光系统是怎么工作的。
