### ISSUE TITLE
Section 3.5 小建议

### ISSUE THREAD

**Issue by wangg12** [gaoxiang12/slam_in_autonomous_driving#35]
1. page 71, 3.5.2 第一段： “更新过程以前协方差矩阵”  中的“以前”应为“以及”？
2. page 73 第一段： “\Delta” 似乎应为 "\delta"
3. page 81, 评注第2点：缺了句号。
4. page 81, 3.5.6第1段: “变为 IMU 积分为递推” 中第二个 “为" 疑似多余
5. page 82, 式（3.73）: 括号多余了

**Comment by gaoxiang12** [comment]
已经确认并修复。
