### ISSUE TITLE
第六章读后感

### ISSUE THREAD

**Issue by yuconglin** [gaoxiang12/slam_in_autonomous_driving#38]
根据2/21更新版本，纯属个人建议。

1. Page 169: “然而，大部分轮机器人的运动方式” 这里“轮”字感觉多余？

2. Page 175: 6.9式 好像需要一个转置才能和Jacobian的定义对上？同样的疑问也存在与6.17, 6.22. 但和代码里面是一致的。代码里面的J其实是转置后的Jacobian.

3. Page 183: 式 6.19 p 的上标不一致。

4. 代码中，https://github.com/gaoxiang12/slam_in_autonomous_driving/blob/master/src/ch6/multi_resolution_likelihood_field.cc#L162 把chi2排序之后好像没有进一步使用？不知道有啥目的。

5. Page 206: 式(6.24) 有误，感觉应该是代码里面所说的 T_S1_S2 = T_S1_C * T_C_W * T_W_S2。

谢谢高博。

**Comment by gaoxiang12** [comment]
已经确认并修复。代码方面还会进一步整理。
