### ISSUE TITLE
关于NDT代码的一个疑问

### ISSUE THREAD

**Issue by yuconglin** [gaoxiang12/slam_in_autonomous_driving#40]
https://github.com/gaoxiang12/slam_in_autonomous_driving/blob/master/src/ch7/ndt_3d.cc#L108 这里key在每个循环中都加了一个grid offset，但是没有被还原。好像不能完全达到遍历原先设想的周围近邻的效果？

**Comment by gaoxiang12** [comment]
感谢指出，已经修复。
