### ISSUE TITLE
关于第七章特征提取的疑惑

### ISSUE THREAD

**Issue by yuconglin** [gaoxiang12/slam_in_autonomous_driving#41]
https://github.com/gaoxiang12/slam_in_autonomous_driving/blob/master/src/ch7/loam-like/feature_extraction.cc#L117 和 https://github.com/gaoxiang12/slam_in_autonomous_driving/blob/master/src/ch7/loam-like/feature_extraction.cc#L108 的意思是：边缘点附近的不平滑点就不被算作边缘点了吗？ 谢谢大家解答。

**Comment by kris6767679** [comment]
这里的思路和LOAM源码一样的，在LOAM论文《Low-drift and Real-time Lidar Odometry and Mapping》的5.1章节中也有提及：“While selecting feature points, we want to avoid points whose surrounded points are selected”。个人理解是：不同类型特征点之间应该相距一段距离，可能是为了提高配准精度。高博书中也提到了，这些特征点法都是工程上总结出来的，没有严格的数学证明为什么要这样做。

**Comment by yuconglin** [comment]
谢谢这位同学的解答。
