### ISSUE TITLE
第三部分读后感

### ISSUE THREAD

**Issue by yuconglin** [gaoxiang12/slam_in_autonomous_driving#52]
根据3/16更新版本。

1. Page 312: (对于式 8.11) “卡尔曼增益左侧部分” 和 “右侧” 应该是“分母部分”和“分子部分”？

2. https://github.com/gaoxiang12/slam_in_autonomous_driving/blob/master/src/ch8/lio-preinteg/lio_preinteg.cc#L410 这里为何+- y的阈值不对称呢？

3. Page 341: “”/bin/dump_map −−pose\_source opti2” 里面pose_source的斜杠应该不需要.加了斜杠好像会导致程序用默认的pose_source设置，就是lidar.

4. Page 342: 图 9-6的地图好像不是根据mapping.yaml里面默认的nclt/20120429.bag 所构建的，好像是20120115.bag。但这个估计也不是啥大问题。

到这里书稿就看完了。谢谢高博写书。

**Comment by gaoxiang12** [comment]
感谢指出，第4条是因为我有时候会改测试数据，导致git上的那个配置文件会改变。其他的已经修复。
另外请把名字和称谓发送给我，我会列到审稿人致谢列表里面。
