### ISSUE TITLE
征集各位读者和审稿人的寄语

### ISSUE THREAD

**Issue by gaoxiang12** [gaoxiang12/slam_in_autonomous_driving#59]
本书在标题后几页设置“推荐语”一节，目前我联系到几位教授来帮忙写了几句推荐语。同时，我也希望能够有读者角度的推荐或者寄语。如果各位审稿同学愿意分享在本书阅读过程中的一些体会，可以收集到本贴，最后会在纸质出版物上体现出来。

- 您可以直接在楼下回复，也可以通过邮件发送给我。
- 您可以添加一个署名，可以是真名也可以是笔名、网名。您也可以同时提供一个称谓，没有也可以。

感谢各位对本书的喜爱与支持！

**Comment by wangg12** [comment]
已发送邮件～
