### ISSUE TITLE
Review of ch4

### ISSUE THREAD

**Issue by zerolover** [gaoxiang12/slam_in_autonomous_driving#60]
- 改成位移、速度、旋转更合适一些
![image](https://user-images.githubusercontent.com/4061122/229974280-ba2fd87b-a949-4502-acac-01d9636a8edf.png)
- 公式错误
![image](https://user-images.githubusercontent.com/4061122/229974401-a32a9121-bbec-41a9-98fd-8ab3ec967fcc.png)
- 下标错误
![image](https://user-images.githubusercontent.com/4061122/229974522-0b7be96e-ea57-4931-aeb2-c7b93cb3957e.png)
- 这里的”加上“和1中的”加上“不是一个意思，但是同时出现在上下文中感觉不太合适
![image](https://user-images.githubusercontent.com/4061122/229974648-69cad6e4-bd92-4506-bebc-d7cf2592f117.png)
- 加粗
![image](https://user-images.githubusercontent.com/4061122/229974989-82349d64-aeaa-4b14-aa54-6923f0938940.png)
- 不同文献当中对残差的具体计算并不完全一致，甚至有的论文和实现**当中**也并不一 致。[去掉当中]
- 下标
![image](https://user-images.githubusercontent.com/4061122/229975210-8713f44f-318e-40dd-bbc2-d9171cd3a3ea.png)

**Comment by gaoxiang12** [comment]
文字部分已经修正。
4.8和4.10这两个，因为bg和ba在i到j之间是认为不变的，所以下标用哪个都是一样的。。噪声项同理。。所以先不动了。

**Comment by zerolover** [comment]
4.8 是括号的问题，没有下标的问题
4.10 的话，我理解 i,j 之间 ba,bg 是不变的(预积分是这么假设的，书上也提到了“我们固定 i 时刻的零偏估计”)，但是噪声项下标应该是不同的。其实就是把 4.10 标出来的三个 i 改成 i+1。
当然写成一样的也行，那就得把诸如 4.11 的噪声项 $\eta_{bg,k}$ 写成 $\eta_{bg,i}$
