### ISSUE TITLE
ch3中关于欧拉角关于delta 角度的求倒

### ISSUE THREAD

**Issue by Vincent-ping** [gaoxiang12/slam_in_autonomous_driving#63]
求问一下，在ch3 eskf.hpp文件中，ObserveSE3函数里对偶拉角求倒不应该是Jl(-theta)吗？为什么会是单位阵，暂时没有高博的新书可以参考，有人能解释下公式3.66是怎么推导的吗

**Comment by gaoxiang12** [comment]
这实际上是一个小trick：

<img width="786" alt="image" src="https://user-images.githubusercontent.com/6635511/233818156-1934ac3d-f0d2-4489-8696-67a9ec1c5ccd.png">
<img width="789" alt="image" src="https://user-images.githubusercontent.com/6635511/233818167-10169411-6e01-4ef1-b57b-7381adf7584e.png">

**Comment by Vincent-ping** [comment]
了解了，感谢高博，另外还有一个问题哈，同样在eskf.hpp中的ObserveWheelSpeed函数中，速度的雅可比矩阵除了对delta v是单位帧外，对姿态是不是是R× v的斜对称矩阵，因为这个vel_world不是通过姿态转到全局的吗？

**Comment by gaoxiang12** [comment]
<img width="788" alt="image" src="https://user-images.githubusercontent.com/6635511/233827319-5c42736f-239a-4c7c-85c3-b5393bbe1ed7.png">

**Comment by Vincent-ping** [comment]
大洋已经准备好了，赶快出版赶快买！！ ！  不过这句话轮速计并没有对R进行物理意义上的测量，这句话怎么理解哈？

**Comment by gaoxiang12** [comment]
因为轮速这个传感器本身没有测量车辆的姿态这种用途啊。。它多数时候只有一个轮子的转速或者转动距离
