### ISSUE TITLE
eskf轮速观测疑问

### ISSUE THREAD

**Issue by SpriteLin-ZJU** [gaoxiang12/slam_in_autonomous_driving#84]
ObserveWheelSpeed中，观测方程v_odom = h(x) = R_-1 * v_ 为什么在计算H矩阵的时候不考虑对R_求导呢？
是因为这里轮速观测用当前R_进行转换作为一个等效观测嘛？
两种写法会有区别么？

**Comment by gaoxiang12** [comment]
因为从原理上来说，轮速并没有对R进行观测，它只是测量轮子的转速，所以不希望它能够影响R的估计。
于是就使用当前R的估计值，将轮速视为直接对v的观测。

**Comment by SpriteLin-ZJU** [comment]
感谢高博解答，
但是我还是有点不明的点就是，虽然只测量的轮子的转速，但是在ESKF使用轮速更新的时候，dx还是会对theta产生影响，您说的“不希望影响R的估计”，那是否在update的时候，dx中除了轮速的其他都应该置为0？

**Comment by SpriteLin-ZJU** [comment]
> 因为从原理上来说，轮速并没有对R进行观测，它只是测量轮子的转速，所以不希望它能够影响R的估计。 于是就使用当前R的估计值，将轮速视为直接对v的观测。

感谢高博解答，
但是我还是有点不明的点就是，虽然只测量的轮子的转速，但是在ESKF使用轮速更新的时候，dx还是会对theta产生影响，您说的“不希望影响R的估计”，那是否在update的时候，dx中除了轮速的其他都应该置为0？
