### ISSUE TITLE
第四章预积分笔误整理，版本：2023.05.06

### ISSUE THREAD

**Issue by ClarkWang1214** [gaoxiang12/slam_in_autonomous_driving#85]
### 1. **p104 公式（4.6a）** ，累乘符号右侧多了一个左括号；
![image](https://github.com/gaoxiang12/slam_in_autonomous_driving/assets/7238759/bdcdeef3-9645-441b-9d36-ef9a22831ce9)
### 2. **p104 公式（4.7c）**，右侧最后一项应该是 $\frac{1}{2}\boldsymbol g\Delta t_{ij}^2$；
![image](https://github.com/gaoxiang12/slam_in_autonomous_driving/assets/7238759/51cf58ea-55af-41f9-a4ba-44336c0984f1)
### 3. **p106 公式（4.10）**，累乘符号展开的第二项陀螺噪声 $\eta_{gd,i}$ 的下标错误，这里固定的是零偏，而不是噪声，应该是 $\eta_{gd,i+1}$ 
![image](https://github.com/gaoxiang12/slam_in_autonomous_driving/assets/7238759/1ae05e55-70a2-4c37-97dc-6af03f0ece4c)
### 4. **p113 公式（4.36）与（4.37）**，两个速度观测相对陀螺加速度计零偏的雅可比，少了波浪号
![image](https://github.com/gaoxiang12/slam_in_autonomous_driving/assets/7238759/147e9bb6-a8a9-4508-b83b-2089e446dc7c)

**Comment by gaoxiang12** [comment]
感谢，已提交给出版社，审阅版本后面不再更新。
