### ISSUE TITLE
thanks for the nice opensource!

### ISSUE THREAD

**Issue by himhan34** [gaoxiang12/slam_in_autonomous_driving#89]
I am curious,are you going to make the book with English as well?
i always thankful for your commitment in this field. thanks!

**Comment by gaoxiang12** [comment]
Yeah, Springer is already asking me to do the translation. But it takes time, and I'm still reviewing the Chinese version now. Maybe I'll start to do the translation in Sep or Oct of 2023.

**Comment by himhan34** [comment]
Thanks for the kind review.
Then are you going to opensource the pdf as well? like before?

**Comment by gaoxiang12** [comment]
There will probably be open-source and hard-copy versions from the publishing house like before because the hard-copy is really expensive for most of the readers.

**Comment by himhan34** [comment]
thanks! i will wait till then. have a nice day!
