### ISSUE TITLE
第一章的一些个人意见

### ISSUE THREAD

**Issue by yuconglin** [gaoxiang12/slam_in_autonomous_driving#9]
第一章：
Page 3: “车辆应该能够在上述信号的识别结果基础上控制车辆的油门、方向盘等执行机构”. 建议加上 “刹车”， 虽然可以被“等” 所代表，但是由于其重要性，单独列出来也比较合理。
Page 3, 4: 图 1-1感觉无法体现出高清地图. 可能出于版权考虑，能用的图片很少。您看https://stacks.stanford.edu/file/druid:zx701jr9713/JesseThesisFinal2-augmented.pdf 里面的图2.2, 2.3能用吗？不知道论文里面的图加上引用的话，书是否能用。
Page 7: 图1-3 和 1-4 不知道是否需要把一些公司的标识给遮掩一下？
Page 10: 其实L2功能为了最后的定位效果，目前也会使用HD map. 参考链接：https://www.ushrauto.com/our-take/2020/3/25/9zs3e4tvotc3rsid34agvr0d6lx037

**Comment by gaoxiang12** [comment]
1. 已经修正，pdf会更新到审稿文件夹中。
2. HDMap在图1-1里还没详细介绍，后文有一些HDMap的图。
3. 要找不带Logo的照片会比较困难，我尽量争取联系到对应的公司来授权吧。
4. Yes，我会补充几句。
